name: KrishiGPT regression

on:
schedule:
- cron: "0 3 * * *" # runs daily at 03:00 UTC
workflow_dispatch: # lets you run it manually from the Actions tab

jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: "3.11"
- run: pip install httpx==0.27.2
- name: Run regression tests
env:
API_URL: https://krishigpt-6bxy.onrender.com
run: python scripts/regression_test.py